I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 73, in script
    $ armor == False
  File "game/script.rpy", line 73, in <module>
    $ armor == False
NameError: name 'armor' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 73, in script
    $ armor == False
  File "E:\renpy\renpy-7.1.1-sdk\renpy\ast.py", line 882, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\renpy\renpy-7.1.1-sdk\renpy\python.py", line 1913, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 73, in <module>
    $ armor == False
NameError: name 'armor' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.1.929
project fantasy alpha 1.0
Tue Nov 13 07:16:56 2018
